Allow psr/simple-cache 3.x
Unleash/unleash-php-sdk pull request #120
Opened 2022-10-12 16:45 UTC by colinodell

# Description

Adds support for using this library with `psr/simple-cache` 2.x and 3.x without breaking backward-compatibility.

Closes #119

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

- [x] Unit tests
- [x] Spec Tests
- [ ] Integration tests / Manual Tests

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-10-12 16:50 UTC, colinodell reviewed
Some notes to assist with your review :)

2022-10-12 16:50 UTC, colinodell commented on .github/workflows/tests.yaml
> +        run: composer require ${{ matrix.optional-deps }}
The matrix will allow us to run these tests twice:

 - Once without `cache/filesystem-adapter` (and therefore using `psr/simple-cache` 3.x)
 - Once with `cache/filesystem-adapter` (and therefore using `psr/simple-cache` 1.x)

Thus giving us confidence that everything works as expected.

2022-10-12 16:50 UTC, colinodell commented on phpstan.neon.dist
> +      reportUnmatched: false
These message will be reported if `cache/filesystem-adapter` is missing, and that's okay.

2022-10-12 16:50 UTC, colinodell commented on tests/Traits/FakeCacheImplementationTrait.php
> +        return new Psr16Cache(new NullAdapter());
`symfony/cache` is already required as a dev dependency, so we can use it's `NullAdapter` which does exactly the same thing, and it gracefully supports `psr/simple-cache` the varied types used in 1.x and 3.x!

2022-10-12 16:50 UTC, colinodell commented on tests/Traits/RealCacheImplementationTrait.php
> +            $this->_cache = new Psr16Cache(new ArrayAdapter());
Similarly, we can use `symfony/cache` here too, which is especially useful now that `cache/filesystem-adapter` may not be installed when the test suite runs.

2022-10-12 16:50 UTC, colinodell commented on tests/UnleashBuilderTest.php
> +        if (class_exists(FilesystemCachePool::class)) {
This looks like a lot of changes, but it's just rearranging existing code and only running `cache/filesystem-adapter`-related tests if it's installed.

2022-10-13 08:58 UTC, sighphyre commented
@colinodell This looks great! Thanks for doing this!

I'm happy with this but I'd like @RikudouSage to take a glance and give the nod

2022-10-13 12:14 UTC, RikudouSage requested changes
This looks great! There's just one small thing and then I'm more than happy to merge!

2022-10-13 12:14 UTC, RikudouSage commented on phpstan.neon.dist
> +      reportUnmatched: false
@colinodell Can you put back the original version of throwing not Throwable? I'd like to ignore that error globally, because it' stupid.

2022-10-14 11:26 UTC, colinodell commented on phpstan.neon.dist
> +      reportUnmatched: false
Sure thing! Fixed via 4121a65.

2022-10-14 11:40 UTC, RikudouSage approved these changes

2022-10-14 11:41 UTC, merged